"""
Tier 2 -> Tier 3 — Redis Message Broker Envelope
Owner: Developer 4 (Webhook Ingestion & Message Broker)
Consumed by: Tier 3 Celery workers (not built tonight — stub consumer only
             needs to deserialize this and ack).

Queue key: `telemetry:ingest` (Redis LIST, LPUSH/BRPOP).
Every webhook the gateway accepts gets wrapped in this envelope before
being pushed. This gives us idempotency + retry without touching the
inner LSAnnotationUpdatedPayload contract.
"""
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, Field, conint

from .label_studio_webhook import LSAnnotationUpdatedPayload


class RedisEventEnvelope(BaseModel):
    event_id: str = Field(..., description="UUID4, generated by the gateway — used as the idempotency key")
    event_type: str = Field("annotation.updated", description="Reserved for future event types")
    idempotency_key: str = Field(..., description="== annotation_id, so replays/duplicate webhooks don't double-queue")
    retry_count: conint(ge=0) = 0
    enqueued_at: str = Field(..., description="ISO-8601 UTC")
    payload: LSAnnotationUpdatedPayload
